### PR TITLE
Add ONT address derivation path

### PR DESCRIPTION
**Pull request by nickfujita**
This is an update made related to the issue filed with the Ontology Ledger app:
https://github.com/LedgerHQ/ledger-app-ont/issues/1

Which was resolved in:
https://github.com/LedgerHQ/ledger-app-ont/commit/76356de89f4f10106a8c11727e4200b7bb9551b8

While the Ontology Ledger app now allows users to use the same address that was created with NEO apps, the Ontology OWallet is still using the ONT BIP44 for address derivation. The reason that this is a problem is that if a user sends any NEO/GAS/NEP5 token to the address created with OWallet, under the ONT BIP44, there is currently not a way to retrieve these funds.

I was proposed that in the near future, OWallet will be updated with functionality for users to enter their Ledger mnemonic phrase to login, but this seems to be against the point of using a Ledger, and will be an ongoing issue. As long as NEO and ONT share the same address schema, users will keep thinking that you can send funds under the same address. Which is true for all non Ledger created addresses, and ones created with the NEO BIP44 today.

The proposed solution is to allow the use of the ONT BIP44 by users of the NEO Ledger app, for the sole purpose of recovering their NEO based funds.

### CODE REVIEW

**Comment by Mankekalanke** [comment]
Thank you very much Nick!

I have the issue you described, hope that this will work out soon, as I am not the only user, who has this problem.

**Comment by Mankekalanke** [comment]
P.S.: using the mnemonic phrase would be no option for any ledger user

**Comment by docolson** [comment]
i guess if nothing else helps i would love to get a manual how to restore my ont with the mnemonic seed - is there already an option somewhere?
since its only one more month to do the swap we need a solution.
would be really happy for some information!

**Comment by jeroenski74** [comment]
Hi docolson,

> i guess if nothing else helps i would love to get a manual how to restore my ont with the mnemonic seed - is there already an option somewhere?

I don't know it this is what you are looking for I hope it helps:

https://steemit.com/cryptocurrency/@pandorasbox/neo-ledger-wif-passphrase-extraction-tool-in-case-you-ever-lose-your-ledger-and-need-to-recover-your-funds

Good luck!

**Comment by Mankekalanke** [comment]
Hi!

Any news regarding the Ledger implementation?

**Comment by Mankekalanke** [comment]
Very bad communication, nobody can tell when the update is implemented! I mean come on TamtamHero, is this the kind of communication you want? what do people who own a ledger device and pay a good some of money to have one think about this??? really bad

**Comment by docolson** [comment]
@nickfujita @TamtamHero would the tool @jeroenski74 posted be an option to retrieve control over nep-5 ont sent to the owallet ledger adress?

here is the link again:
https://steemit.com/cryptocurrency/@pandorasbox/neo-ledger-wif-passphrase-extraction-tool-in-case-you-ever-lose-your-ledger-and-need-to-recover-your-funds

**Comment by docolson** [comment]
> @nickfujita @TamtamHero would the tool @jeroenski74 posted be an option to retrieve control over nep-5 ont sent to the owallet ledger adress?
> 
> here is the link again:
> https://steemit.com/cryptocurrency/@pandorasbox/neo-ledger-wif-passphrase-extraction-tool-in-case-you-ever-lose-your-ledger-and-need-to-recover-your-funds

the new version of o3 wallet worked - Thanks!!!

**Pull request merged**
